version: "3"
services:
  autoindex_prev:
    image: zongzw/nginx-njs:latest
    build: ${HOMEDIR}
    container_name: autoindex_prev
    ports:
      - 8091:80
    volumes:
      - ${AUTOINDEX_PREV}/nginx.conf:/root/nginx/conf/nginx.conf
      - ${AUTOINDEX_PREV}/src:/root/nginx/conf/scripts
      - ${AUTOINDEX_PREV}/data:/root/data

  data_masking:
    image: zongzw/nginx-njs:latest
    build: ${HOMEDIR}
    container_name: data_masking
    ports:
      - 8092:80
    volumes:
      - ${DATA_MASKING}/nginx.conf:/root/nginx/conf/nginx.conf
      - ${DATA_MASKING}/masking.js:/root/nginx/conf/scripts/masking.js

  virtual_patching:
    image: zongzw/nginx-njs:latest
    build: ${HOMEDIR}
    container_name: virtual_patching
    ports:
      - 8093:80
    volumes:
      - ${VIRTUAL_PATCHING}/nginx.conf:/root/nginx/conf/nginx.conf
      - ${VIRTUAL_PATCHING}/patching.js:/root/nginx/conf/scripts/patching.js
      - ${VIRTUAL_PATCHING}/kps:/root/nginx/conf/kps

  fast_response:
    image: zongzw/nginx-njs:latest
    build: ${HOMEDIR}
    container_name: fast_response
    ports:
      - 8094:80
    volumes:
      - ${FAST_RESPONSE}/nginx.conf:/root/nginx/conf/nginx.conf
      - ${FAST_RESPONSE}/response.js:/root/nginx/conf/scripts/response.js