version: "3"
services:
  autoindex_prev:
    image: zongzw/nginx-njs:latest
    build: ${HOMEDIR}
    container_name: autoindex_prev
    ports:
      - 8091:80
    volumes:
      - ${AUTOINDEX_PREV}/nginx.conf:/root/nginx/conf/nginx.conf
      - ${AUTOINDEX_PREV}/src:/root/nginx/conf/scripts
      - ${AUTOINDEX_PREV}/data:/root/data

  data_masking:
    image: zongzw/nginx-njs:latest
    build: ${HOMEDIR}
    container_name: data_masking
    ports:
      - 8092:80
    volumes:
      - ${DATA_MASKING}/nginx.conf:/root/nginx/conf/nginx.conf
      - ${DATA_MASKING}/masking.js:/root/nginx/conf/scripts/masking.js

  virtual_patching:
    image: zongzw/nginx-njs:latest
    build: ${HOMEDIR}
    container_name: virtual_patching
    ports:
      - 8093:80
    volumes:
      - ${VIRTUAL_PATCHING}/nginx.conf:/root/nginx/conf/nginx.conf
      - ${VIRTUAL_PATCHING}/patching.js:/root/nginx/conf/scripts/patching.js
      - ${VIRTUAL_PATCHING}/kps:/root/nginx/conf/kps

  fast_response:
    image: zongzw/nginx-njs:latest
    build: ${HOMEDIR}
    container_name: fast_response
    ports:
      - 8094:80
    volumes:
      - ${FAST_RESPONSE}/nginx.conf:/root/nginx/conf/nginx.conf
      - ${FAST_RESPONSE}/response.js:/root/nginx/conf/scripts/response.js

  json_logging:
    image: zongzw/nginx-njs:latest
    build: ${HOMEDIR}
    container_name: json_logging
    ports:
      - 8095:80
    volumes:
      - ${JSON_LOGGING}/nginx.conf:/root/nginx/conf/nginx.conf
      - ${JSON_LOGGING}/logging.js:/root/nginx/conf/scripts/logging.js

  file_opera:
    image: zongzw/nginx-njs:latest
    build: ${HOMEDIR}
    container_name: file_opera
    ports:
      - 8096:80
    volumes:
      - ${FILE_OPERA}/nginx.conf:/root/nginx/conf/nginx.conf
      - ${FILE_OPERA}/fileops.js:/root/nginx/conf/scripts/fileops.js
      - ${FILE_OPERA}/data:/root/nginx/conf/data

  batching_request:
    image: zongzw/nginx-njs:latest
    build: ${HOMEDIR}
    container_name: batching_request
    ports:
      - 8097:80
    volumes:
      - ${BATCHING_REQUEST}/nginx.conf:/root/nginx/conf/nginx.conf
      - ${BATCHING_REQUEST}/batching.js:/root/nginx/conf/scripts/batching.js
      - ${BATCHING_REQUEST}/data:/root/nginx/conf/data
      - ${BATCHING_REQUEST}/favicon.ico:/root/nginx/conf/favicon.ico

  auditting_defacement:
    image: zongzw/nginx-njs:latest
    build: ${HOMEDIR}
    container_name: auditting_defacement
    ports:
      - 8098:80
    volumes:
      - ${AUDITTING_DEFACEMENT}/nginx.conf:/root/nginx/conf/nginx.conf
      - ${AUDITTING_DEFACEMENT}/audit.js:/root/nginx/conf/scripts/audit.js
  
  validate_request:
    image: zongzw/nginx-njs:latest
    build: ${HOMEDIR}
    container_name: validate_request
    ports:
      - 8099:80
    volumes:
      - ${VALIDATE_REQUEST}/nginx.conf:/root/nginx/conf/nginx.conf
      - ${VALIDATE_REQUEST}/validate.js:/root/nginx/conf/scripts/validate.js

  payload_proxy:
    image: zongzw/nginx-njs:latest
    build: ${HOMEDIR}
    container_name: payload_proxy
    ports:
      - 8100:80
    volumes:
      - ${PAYLOAD_PROXY}/nginx.conf:/root/nginx/conf/nginx.conf
      - ${PAYLOAD_PROXY}/payload.js:/root/nginx/conf/scripts/payload.js

  ftp_1pasv_alg:
    image: zongzw/nginx-njs:latest
    build: ${HOMEDIR}
    container_name: ftp_1pasv_alg
    ports:
      - "8121:21"
      - "$NGX_1PASV_PORT:$NGX_1PASV_PORT"
    volumes:
      - ${FTP_1PASV_ALG}/nginx.conf:/root/nginx/conf/nginx.conf
      - ${FTP_1PASV_ALG}/ftp.js:/root/nginx/conf/scripts/ftp.js
    depends_on:
      - myftp_1pasv
    environment:
      # the host ipaddr compared with this container's.
      # only dotted IP, cannot be hostname
      - HOST_ADDRESS=${HOST_ADDRESS:-127.0.0.1}
      # ftp port in passive mode for data transformation.
      - FTP_1PASV_PORT=$FTP_1PASV_PORT
      - NGX_1PASV_PORT=$NGX_1PASV_PORT

  myftp_1pasv:
    image: fauria/vsftpd:latest
    container_name: myftp_1pasv
    ports:
      - "$FTP_1PASV_PORT"
      - "21"
    environment:
      - FTP_USER=zongzw
      - FTP_PASS=123
      - PASV_ADDRESS=localhost
      - PASV_ADDR_RESOLVE=YES
      - PASV_MIN_PORT=$FTP_1PASV_PORT
      - PASV_MAX_PORT=$FTP_1PASV_PORT
      - LOG_STDOUT=YES
    volumes:
      - ${FTP_1PASV_ALG}/shared:/home/vsftpd

  ftp_npasv_alg:
    image: zongzw/nginx-njs:latest
    build: ${HOMEDIR}
    container_name: ftp_npasv_alg
    ports:
      - "8122:21"
      - "$FTP_NPASV_PORTS:$FTP_NPASV_PORTS"
    volumes:
      - ${FTP_NPASV_ALG}/nginx.conf:/root/nginx/conf/nginx.conf
      - ${FTP_NPASV_ALG}/ftp.js:/root/nginx/conf/scripts/ftp.js
    depends_on:
      - myftp_npasv
    environment:
      # the host ipaddr compared with this container's.
      # only dotted IP, cannot be hostname
      - HOST_ADDRESS=${HOST_ADDRESS:-127.0.0.1}
      # ftp port in passive mode for data transformation.
      # default to 20001-20010

  myftp_npasv:
    image: fauria/vsftpd:latest
    container_name: myftp_npasv
    ports:
      - "$FTP_NPASV_PORTS"
      - "21"
      # - "$FTP_NPASV_PORTS:$FTP_NPASV_PORTS"
      # - "21:21"
    environment:
      - FTP_USER=zongzw
      - FTP_PASS=123
      - PASV_ADDRESS=localhost
      - PASV_ADDR_RESOLVE=YES
      - PASV_MIN_PORT=$FTP_NPASV_PORT_START
      - PASV_MAX_PORT=$FTP_NPASV_PORT_END
      - LOG_STDOUT=YES
    volumes:
      - ${FTP_NPASV_ALG}/shared:/home/vsftpd