version: "3"
services:
  autoindex_prev:
    image: zongzw/nginx-njs:latest
    build: ${HOMEDIR}
    container_name: autoindex_prev
    ports:
      - 8089:80
    volumes:
      - ${AUTOINDEX_PREV}/nginx.conf:/root/nginx/conf/nginx.conf
      - ${AUTOINDEX_PREV}/src:/root/nginx/conf/scripts
      - ${AUTOINDEX_PREV}/data:/root/data
