version: "3"
services:
  fast_response:
    image: nginx:1.21.1
    container_name: fast_response
    ports:
      - 8094:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./response.js:/etc/nginx/scripts/response.js
    entrypoint: nginx