version: "3"
services:
  uuid_browserify_test:
    image: nginx:1.21.1
    container_name: uuid_browserify_test
    ports:
      - 8902:80
    volumes:
      - ${HOMEDIR}/6.njs-bundle.js:/etc/nginx/njs_bundle.js
      - ${HOMEDIR}/7.nginx.conf:/etc/nginx/nginx.conf
    entrypoint: nginx