version: "3"
services:
  batching_request:
    image: nginx:1.21.1
    container_name: batching_request
    ports:
      - 8097:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./batching.js:/etc/nginx/scripts/batching.js
      - ./data:/root/nginx/conf/data
      - ./favicon.ico:/root/nginx/conf/favicon.ico
    entrypoint: nginx